#file type
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup   = 1
'''

# auto close
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
